const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '..')
const desktop = require('./package.json')
const release = require('../version.json')
const updatePolicy = require('./update-policy.cjs')
const required = ['frontend/dist/index.html', 'backend/main.py', '.venv/Scripts/pythonw.exe', 'desktop/assets/app-icon.ico', 'desktop/update-policy.cjs']
const missing = required.filter(file => !fs.existsSync(path.join(root, file)))
if (desktop.version !== release.version) throw new Error(`版本不一致: desktop=${desktop.version}, root=${release.version}`)
if (missing.length) throw new Error(`缺少运行文件: ${missing.join(', ')}`)
if (desktop.build.appId !== 'com.tradingai.marketassistant') throw new Error('appId 不得在升级版本之间变化。')
if (desktop.build.nsis.shortcutName !== desktop.productName || desktop.build.nsis.createDesktopShortcut !== 'always') throw new Error('桌面快捷方式配置无效。')
if (desktop.build.nsis.oneClick !== true || desktop.build.nsis.perMachine !== false) throw new Error('NSIS 必须使用当前用户的一键安装，不能再次显示安装选项。')
if (!updatePolicy.INSTALL_OPTIONS.isSilent || !updatePolicy.INSTALL_OPTIONS.isForceRunAfter) throw new Error('自动更新必须静默安装并启动应用程序。')
if (!updatePolicy.isStrictlyNewerVersion('1.0.1', '1.0.0')) throw new Error('1.0.0 -> 1.0.1 版本判断失败。')
if (updatePolicy.isStrictlyNewerVersion('1.0.1', '1.0.1')) throw new Error('相同版本不得重复安装。')
if (updatePolicy.isStrictlyNewerVersion('1.0.0', '1.0.1')) throw new Error('旧版本不得覆盖新版本。')
console.log(`Desktop verified: ${desktop.productName} v${desktop.version}; shortcut/silent-update/version-policy PASS`)
